# Generated by Django 5.2.8 on 2025-11-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_animals', models.IntegerField()),
                ('pending_requests', models.IntegerField()),
                ('adoptions', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_dogs', models.IntegerField()),
                ('total_cats', models.IntegerField()),
                ('total_pets', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PENDING', 'Pending'), ('ADOPTED', 'Adopted')], default='AVAILABLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('is_availale', models.BooleanField(default=True)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('weight', models.FloatField()),
                ('distance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('pet_details', models.CharField(max_length=100)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('req_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PENDING', 'Pending'), ('ADOPTED', 'Adopted')], default='AVAILABLE', max_length=20)),
            ],
        ),
    ]
