# Generated by Django 5.2.8 on 2025-11-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_facility_gender_alter_pets_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='name',
        ),
    ]
