# Generated by Django 5.2.8 on 2025-11-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_inventory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='type',
        ),
    ]
