# Generated by Django 5.2.8 on 2025-11-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_adoptregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptregistration',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
