# Generated by Django 5.2.8 on 2025-11-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_adoptregistration_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptregistration',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
