# Generated by Django 5.2.8 on 2025-11-25 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_adoptregistration_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptregistration',
            name='password',
        ),
        migrations.RemoveField(
            model_name='adoptregistration',
            name='username',
        ),
        migrations.AddField(
            model_name='adoptregistration',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
