# Generated by Django 5.2.8 on 2025-11-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_adoptregistration_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptregistration',
            name='user',
        ),
        migrations.AddField(
            model_name='adoptregistration',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adoptregistration',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adoptregistration',
            name='fullname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
