# Generated by Django 5.2.8 on 2025-11-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_adoptregistration_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adoptregistration',
        ),
    ]
