# Generated by Django 5.2.6 on 2025-11-29 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_inventory_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FosterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('full_address', models.CharField(blank=True, max_length=255)),
                ('household_description', models.TextField(blank=True)),
                ('profile_image_url', models.URLField(blank=True, max_length=500)),
                ('pet_preferences', models.CharField(blank=True, help_text='Comma-separated pet preferences (e.g., Small Dogs, Calm Cats)', max_length=255)),
                ('is_foster', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
