# Generated by Django 5.2.8 on 2025-11-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_inventory', '0002_adoptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
    ]
