# Generated by Django 5.2.6 on 2025-11-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_inventory', '0010_pet_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
