# Generated by Django 5.2.6 on 2025-11-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_inventory', '0011_pet_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('adopter', 'Adopter'), ('poster', 'Poster'), ('foster', 'Foster')], max_length=20),
        ),
    ]
