# Generated by Django 5.2.6 on 2025-11-30 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_inventory', '0012_alter_account_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FosterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(help_text='The name displayed on the public profile.', max_length=255, verbose_name='User Name for Display')),
                ('email', models.EmailField(help_text="Foster's primary contact email.", max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField(help_text='Full address (or relevant general location).')),
                ('household', models.TextField(help_text="Description of the foster's living situation (e.g., family size, environment).")),
                ('profileImage', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foster Profile',
                'verbose_name_plural': 'Foster Profiles',
            },
        ),
        migrations.CreateModel(
            name='FosterPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(help_text='e.g., Dog, Cat, Bird.', max_length=50)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.CharField(help_text="e.g., '6 Months', '2 Years'.", max_length=50)),
                ('foster_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_fosters', to='admin_inventory.fosterprofile')),
            ],
            options={
                'verbose_name': 'Foster Pet',
                'verbose_name_plural': 'Foster Pets',
            },
        ),
    ]
