# Generated by Django 5.2.6 on 2025-11-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_inventory', '0013_fosterprofile_fosterpet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fosterprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='FosterPet',
        ),
        migrations.DeleteModel(
            name='FosterProfile',
        ),
    ]
