# Generated by Django 5.2.6 on 2025-12-02 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_inventory', '0017_userprofile_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='FosterCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='admin_inventory.fosterprofile')),
            ],
        ),
    ]
