# Generated by Django 5.2.6 on 2025-12-05 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_inventory', '0018_fostercertification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FosterCertification',
        ),
    ]
